# Generated by Django 5.2 on 2025-05-05 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_defaultuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FOLLOWING', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='forward_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FOLLOWER', to=settings.AUTH_USER_MODEL),
        ),
    ]
