# Generated by Django 5.2 on 2025-05-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_defaultuser_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PROFILE', to=settings.AUTH_USER_MODEL),
        ),
    ]
